resources:
- name: music-repo
  type: git
  source:
    uri: git@github.com:klng19/spring-music.git
    branch: master
    private_key: {{music_private_key}}
- name: version
  type: semver
  source:
    bucket: {{music-pipeline-artifacts-bucket}}
    endpoint: {{s3-endpoint}}
    key: current-version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    initial_version: 1.0.0
jobs:
- name: unit
  plan:
  - get: music-repo
    trigger: true
  - task: unit
    file: music-repo/ci/tasks/unit.yml

- name: build-binary
  serial: true
  plan:
  - get: music-repo
    passed: [unit]
    trigger: true
  - get: version
    params: {bump: patch}
  - task: build-artifact
    file: music-repo/ci/tasks/build-artifact.yml
    timeout: 5m
